# Generated by Django 5.1.2 on 2024-10-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizado_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='Sin especialidad', help_text='Especialidad del Director General', max_length=100),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Ciudad por defecto', help_text='Ciudad donde se encuentra el laboratorio', max_length=100),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='País por defecto', help_text='País donde se encuentra el laboratorio', max_length=100),
        ),
    ]
